# The Basics (creating arrays, shape, size, data type)

In [ ]:
# importando numpy
import numpy as np

Criando array unidimencional

In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


Criando array com duas dimensões

In [ ]:
b = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]])
print(b)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


Pegando o número de dimenções

In [ ]:
# a
a.ndim

1

In [ ]:
# b
b.ndim

2

Pegando o shape

In [ ]:
# a
a.shape

(7,)

In [ ]:
# b
b.shape

(2, 7)

Pegando o type

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

Pegando o size

In [ ]:
a.itemsize

8

In [ ]:
b.itemsize

8

## Definindo o dataType

In [ ]:
a = np.array([1,2,3,4,5,6,7], dtype='int16')
b = np.array([[1,2,3,4,5,6,7],[7,6,5,4,3,2,1]],dtype='int32')

print(a.itemsize)
print(b.itemsize)

2
4


## Pegando o tamanho total

In [ ]:
a.nbytes

14

In [ ]:
b.nbytes

56