# Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [ ]:
import numpy as np

Criando array multidimensional

In [ ]:
 a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Pegando um elemento específico

In [ ]:
a[2,1]

12

In [ ]:
a[-1,-4]

12

Pegando uma linha

In [ ]:
a[0,:]

array([1, 2, 3, 4, 5])

Pegando uma coluna

In [ ]:
a[:,0]

array([ 1,  6, 11])

[indice inicial: até indice final, intervalo]

In [ ]:
a[1, 0:5:2]

array([ 6,  8, 10])

In [ ]:
a[1, 0:-1:1]

array([6, 7, 8, 9])

Mudando o valor de um elemento

In [ ]:
a[0,0] = -1
a[0,1] = -2
a[0,2] = -3
a[0,3] = -4
a[0,4] = -5

In [ ]:
print(a)

[[-1 -2 -3 -4 -5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
a[0,:] = 34
print(a)

[[34 34 34 34 34]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
a[0,:] = [1,2,3,4,5]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Array 3d

In [ ]:
b = np.array([[[111,112,113],[121,122,123],[131,132,133]],[[211,212,213],[221,222,223],[231,232,233]],[[311,312,313],[321,322,323],[331,332,333]]])
b

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

Pegando o número 123

In [ ]:
b[0,1,2]

123

In [ ]:
# pegou os arrays e estavam na coordenada x=0
# todos têm 1 nas centenas
b[0,:,:]

array([[111, 112, 113],
       [121, 122, 123],
       [131, 132, 133]])

In [ ]:
# pegou os arrays e estavam na coordenada y=0
# todos tem 1 nas dezenas
b[:,0,:]

array([[111, 112, 113],
       [211, 212, 213],
       [311, 312, 313]])

In [ ]:
# pegou os arrays e estavam na coordenada z=0
# todos tem 1 nas unidades
b[:,:,0]

array([[111, 121, 131],
       [211, 221, 231],
       [311, 321, 331]])

Alterando valores

In [ ]:
# onde y=1 
print(b[:,1,:])

[[121 122 123]
 [221 222 223]
 [321 322 323]]


In [ ]:
b[:,1,:] = [[-121, -122, -123],
       [-221, -222, -223],
       [-321, -322, -323]]

In [ ]:
print(b[:,1,:])

[[-121 -122 -123]
 [-221 -222 -223]
 [-321 -322 -323]]


In [ ]:
print(b)

[[[ 111  112  113]
  [-121 -122 -123]
  [ 131  132  133]]

 [[ 211  212  213]
  [-221 -222 -223]
  [ 231  232  233]]

 [[ 311  312  313]
  [-321 -322 -323]
  [ 331  332  333]]]
