# Initializing Different Arrays (1s, 0s, full, random, etc...)

In [ ]:
import numpy as np

Criando um array de zeros

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))
# gera um array de 2 dimensões

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3,3))
# gera um array de 3 dimensões

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros((3,3,3,3))
# gera um array de 4 dimensões

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

array com 1s

In [ ]:
np.ones((3,3),dtype='int16')
# também é possível especificar o datatype

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

Criando array formado apenas por um número específico

In [ ]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

Criando a partir de um shape específico

In [ ]:
a = np.array([[[111,112],[121,122]],[[211,212],[221,222]]])
#array 2x2x2
print(a)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]]


In [ ]:
np.full_like(a,3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

Números decimais randômicos

In [ ]:
np.random.rand(2,2)

array([[0.82392491, 0.88765731],
       [0.09244577, 0.18884669]])

In [ ]:
np.random.rand(2,2,3)

array([[[0.57245556, 0.15895   , 0.80836412],
        [0.87542352, 0.09066231, 0.29327346]],

       [[0.48193659, 0.31662712, 0.74788978],
        [0.22953082, 0.30804379, 0.39361167]]])

In [ ]:
# pegando o shape
np.random.random_sample(a.shape)

array([[[0.64926334, 0.50158205],
        [0.83180304, 0.85686115]],

       [[0.86618048, 0.04267763],
        [0.46382411, 0.38055835]]])

Random de inteiros

In [ ]:
np.random.randint(10,20) #retorna números entre 10 e 29

17

In [ ]:
np.random.randint(1,20,size=(3,3)) # gera um array 3x3

array([[ 1,  3,  6],
       [16,  8, 12],
       [10, 19,  5]])

Criando matriz identidade

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Repetindo arrays

In [ ]:
arr = np.array([[1,2,3,4]])# criando array bidimensional
r1 = np.repeat(arr,4, axis=0) #vai repetir o array 4 vezes no eixo 0
print(r1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
r2 = np.repeat(arr,4, axis=1) #vai repetir o array 4 vezes no eixo 1
print(r2)

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]]
