# Basic Mathematics (arithmetic, trigonometry, etc.)

In [ ]:
import numpy as np

Adição, subração, divisão e mutiplicação

In [ ]:
a = np.array([1,2,3])
a + 10 # Adiciona 10 a cada elemento

array([11, 12, 13])

In [ ]:
a = np.array([1,2,3])
a - 10 # Subtrai 10 de cada elemento

array([-9, -8, -7])

In [ ]:
a = np.array([1,2,3])
a * 10 # multiplica por 10 cada elemento

array([10, 20, 30])

In [ ]:
a = np.array([1,2,3])
a / 10 # Divide por 10 cada elemento

array([0.1, 0.2, 0.3])

Oparações com mais de um array

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

a+b # soma cada elemento com seu índice equivalente

array([6, 6, 6, 6, 6])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

a-b # reduz cada elemento por seu índice equivalente

array([-4, -2,  0,  2,  4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

a*b # multiplica cada elemento por seu índice equivalente

array([5, 8, 9, 8, 5])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

a/b # divide cada elemento por seu índice equivalente

array([0.2, 0.5, 1. , 2. , 5. ])

potencias

In [ ]:
a = np.array([1,2,3])
a ** 2 # eleva todos ao quadrado

array([1, 4, 9])

Seno

In [ ]:
a = np.array([0, np.pi/2, 5, 8])
np.sin(a)# Pega o seno de cada número

array([ 0.        ,  1.        , -0.95892427,  0.98935825])

Cosseno

In [ ]:
a = np.array([0, np.pi/2, 5, 8])
np.cos(a)# Pega o cosseno de cada número

array([ 1.00000000e+00,  6.12323400e-17,  2.83662185e-01, -1.45500034e-01])