# Statistics

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.min(a) #Vai retonar o valor mínimo

1

In [7]:
np.min(a, axis=1) #Vai retonar o valor mínimo de cada linha

array([1, 4])

In [5]:
np.max(a) #Vai retonar o valor máximo

6

In [10]:
np.max(a, axis=0) #Vai retonar o valor máximo por coluna

array([4, 5, 6])

In [6]:
np.mean(a) #Vai retonar a média

3.5

In [9]:
np.mean(a, axis=1) #Vai retonar a média de cada linha

array([2., 5.])

In [11]:
np.sum(a) # retorna a soma total

21