# Reorganizing Arrays (reshape, vstack, hstack)

In [1]:
import numpy as np

In [4]:
antes = np.array([[1,2,3,4],[5,6,7,8]])
antes.shape # informa que exitem 2 linhas e 4 colunas

(2, 4)

In [6]:
depois = antes.reshape(1,8) # coloca todos em uma linha
depois

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
depois = antes.reshape(4,2)
depois

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
depois = antes.reshape(2,2,2) # cria uma matriz tridimensional
depois

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Empilhamento vertical

In [11]:
l1 = np.array([1,2,3,4])
l2 = np.array([5,6,7,8])

np.vstack([l1,l1,l2,l2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

Empilhamento horizontal

In [16]:
c1 = np.array([[1],[2],[3]])
c2 = np.array([[4],[5],[6]])

np.hstack([c1,c2])

array([[1, 4],
       [2, 5],
       [3, 6]])