# Load data in from a file

In [ ]:
import numpy as np

In [ ]:
filedata = np.genfromtxt('data.txt',delimiter=',')

filedata = filedata.astype(np.int32) # converte para int32
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

# Advanced Indexing and Boolean Masking

In [10]:
filedata > 20 # Retorna se os elementos são maiores que 20

array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [17]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[2,3,4]] # Pegando posições específicas

array([3, 4, 5])

In [12]:
filedata[filedata>20] # Retorna os elementos maiores que 20

array([ 21, 196,  75,  34,  42,  33, 766,  75,  55,  22,  33, 999,  78,
        76,  88], dtype=int32)

In [19]:
np.any(filedata> 40, axis=0) # Retora se a coluna tem pelo menos um valor maior que 40

array([False,  True, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [20]:
np.all(filedata> 40, axis=0) # Retora se a coluna tem pelo todos os malores maiores que 40

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [21]:
((filedata>50) & (filedata<100)) # testa com o operador and

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [22]:
(~(filedata>50) & (filedata<100)) # Usa o operador de necação ~

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])